# Generated by Django 4.2.8 on 2025-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "metal_type",
                    models.CharField(
                        choices=[("gold", "Gold"), ("silver", "Silver")], max_length=10
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "metal_type")},
            },
        ),
    ]
